version: '3'
services:
  jekyll:
    image: ruby:3.3
    ports:
      - "4000:4000"
    volumes:
      - .:/opt/docs
    working_dir: /opt/docs
    command: sh -c "bundle install && bundle exec jekyll serve --config _config.yml --host '0.0.0.0'"